name: Remote Build for vps
on:
  schedule:
    - cron: 0 20 1 * *
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled"
        required: false
        default: false

env:
  NIX_PATH: nixpkgs=channel:nixos-unstable
  TZ: Asia/Shanghai
  # NIXPKGS_ALLOW_BROKEN: 1
  # NIXPKGS_ALLOW_INSECURE: 1
  NIX_SSHOPTS: "-o StrictHostKeyChecking=no -p 2022"

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        hosts: [osaka-1, osaka-2, tokyo-1, tokyo-2, claw, natvps, alice, sailor]
    steps:
      - name: Delete older workflow runs and artifacts
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: SSH Private Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install nixFlake
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            trusted-public-keys = zenqy.cachix.org-1:G5csLBsu/kQIOXU7XUiqeMacwzN1WQWv0+GysTVmJgo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://zenqy.cachix.org/ https://cache.nixos.org/

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Use Cachix
        uses: cachix/cachix-action@v15
        with:
          name: zenqy
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: host env
        run: |
          host=$(echo ${{ matrix.hosts }} | sed 's/-/_/g' | awk '{print toupper ($0)}')
          echo HOST=$host >> $GITHUB_ENV

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: remote build
        run: |
          nix-env -f '<nixpkgs>' -iA nixos-rebuild
          nixos-rebuild test --flake .#${{ matrix.hosts }} --target-host root@${{ secrets[env.HOST] }}

      - name: Telegram notification
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            [${{ matrix.hosts }}]编译失败，请查明原因
